/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as EditorDocumentIdImport } from './routes/editor/$documentId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EditorDocumentIdRoute = EditorDocumentIdImport.update({
  id: '/editor/$documentId',
  path: '/editor/$documentId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/editor/$documentId': {
      id: '/editor/$documentId'
      path: '/editor/$documentId'
      fullPath: '/editor/$documentId'
      preLoaderRoute: typeof EditorDocumentIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor/$documentId': typeof EditorDocumentIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor/$documentId': typeof EditorDocumentIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/editor/$documentId': typeof EditorDocumentIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor/$documentId'
  id: '__root__' | '/' | '/editor/$documentId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorDocumentIdRoute: typeof EditorDocumentIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorDocumentIdRoute: EditorDocumentIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/editor/$documentId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/editor/$documentId": {
      "filePath": "editor/$documentId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
